.TH neutre 1
.SH NAME
neutre \- CLI to spelunk logs of Neutraliza web server
.SH SYNOPSIS
.B neutre
.ul
LOG_TYPE
.ul
FORMAT
.br
.B neutre
[OPTIONS]
.SH DESCRIPTION
This is a simple script to find, list and digest the logs generated during the operation of the Neutraliza web server.
.SH OPTIONS
.TP
.BR h
Print Hello
.TP
.BR b 
Print Bye
.SH LOG_TYPE
.TP
.BR h
Print Hello
.TP
.BR b 
Print Bye
.SH AUTHOR
Written by roaraujo | Rods (Rodrigo Gregoldo) - github.com/rodsmade
.SH COPYRIGHT
You may copy away at will. Here's to fearless enjoyment...